230419 나무자르기
AlGotIt/Algorithm2023 pull request #15
Opened 2023-04-23 13:39 UTC by Yeeunbb

## Problem Description

<br>
BOJn 2805 나무자르기 (https://www.acmicpc.net/problem/2805)

## Explain Process

<br>
- 문제를 해결한 방법 간단하게 정리
이분탐색으로 해결. 입력받은 나무 중 가장 큰 나무의 1/2 지점을 기준으로 잡고 잘라보면서, 가능한 가장 높은 위치의 자르는 지점을 구한다.

### Comment

2023-04-25 00:32 UTC, melli0505 requested changes
굿굿 수고하셨습니다~ .vscode 폴더만 삭제해주세용

2023-04-25 00:32 UTC, melli0505 commented on .vscode/launch.json
> +{
들어가면 안될 파일이 왔어요~!~!~!~!~

2023-05-03 16:21 UTC, Yeeunbb commented on .vscode/launch.json
> +{
.gitignore가 작동을 안하나바여 ㅠ 수정 부탁

2023-05-17 13:45 UTC, melli0505 approved these changes
굿~

2023-05-17 13:45 UTC, melli0505 approved these changes
굿~

2023-05-17 13:45 UTC, melli0505 approved these changes
굿~

2023-05-17 13:58 UTC, merged